### ISSUE TITLE
Always says "You do not have permission to use"

### ISSUE THREAD

**Issue by jemiller226** [JoelGodOfwar/SinglePlayerSleep#4]
I was under the impression that everyone, by default, got permission to use the bed. Plus, I'm an op and I should thus have access to the /sleep command, but I don't. What gives?

**Comment by jemiller226** [comment]
Switched to the Java 8 version, as I realized the server was running that. It now says, "An internal error occurred..."

Here's the log from the console:

[18:31:04 INFO]: SC_Findecano issued server command: /sleep
[18:31:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sleep' in plugin SinglePlayerSleep v2.13.13-1.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-7d78b81-d5e7885]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [server.jar:git-Spigot-7d78b81-d5e7885]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [server.jar:git-Spigot-7d78b81-d5e7885]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/Packet
	at com.github.joelgodofwar.sps.PluginBase.onCommand(PluginBase.java:347) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at com.github.joelgodofwar.sps.PluginBase.onCommand(PluginBase.java:347) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-7d78b81-d5e7885]
	... 15 more

**Comment by JoelGodOfwar** [comment]
Assuming this was fixed, since no new posts have been made.
