### ISSUE TITLE
Latest version breaks the plugin

### ISSUE THREAD

**Issue by YeapGuy** [JoelGodOfwar/SinglePlayerSleep#8]
After updating to the latest version of the plugin, each time a player enters a bed, this error shows up in the console:
```
[19:03:59 ERROR]: Could not pass event PlayerBedEnterEvent to SinglePlayerSleep v2.13.15
java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/Packet
at com.github.joelgodofwar.sps.PluginBase.PlayerIsSleeping(PluginBase.java:164) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor12.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-209]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:258) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.EntityHuman.sleep(EntityHuman.java:1295) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:1020) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:1014) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.BlockBed.interact(BlockBed.java:55) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:226) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:487) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-209]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-209]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.Packet
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.14.4.jar:git-Paper-209]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-209]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 27 more 
```

Could you take a look at it please? Thanks.

EDIT: I fixed the formatting

**Comment by JoelGodOfwar** [comment]
What server version are you running? I see references to both 1.11 and 1.14.4. Version 2.13.15 of my plugin is only for minecraft version 1.11. Running with debug=true in the config file will give more information. If you're running 1.14.4 then you need the newest version 2.13.23 found at https://www.spigotmc.org/resources/single-player-sleep.68139/ or https://dev.bukkit.org/projects/singleplayersleep2 otherwise if you're running 1.11 you may need to update the java version.

**Comment by YeapGuy** [comment]
The server is 1.14.4, nothing to do with 1.11. I have (or had, since I
downgraded to the previous version to fix the issue) the latest version of
SinglePlayerSleep, for 1.14, from Spigot's plugin repo.
Anyway, I'll turn on the debug and send you the error afterwards.

**Comment by JoelGodOfwar** [comment]
SinglePlayerSleep 2.13.15 is for Minecraft 1.11, you need 2.13.19b, 2.13.21, or the newest 2.13.23 available at https://www.spigotmc.org/resources/single-player-sleep.68139/

**Comment by YeapGuy** [comment]
Yeah, that's what I used. The latest one from SpigotMC's plugins site.

**Comment by YeapGuy** [comment]
Oops, nevermind!
For some strange reason, I've apparently got a broken .jar. It didn't have the version number in the filename and it did the strange error you saw above. I downloaded it again, now it has the version number and it works perfectly!
Sorry for the annoyance and thanks for trying to troubleshoot!
